on: 
  push:
    branches:
    - '*'
    - '!status'
    - '!feedback'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  issue_comment:
    types: [created]

    
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      # add id to action so outputs can be used
      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      # switch to badges branch
      - run: git checkout scores || git checkout -b scores

      - name: scores
        run: |
          echo `date` > .github/scores
          echo ${{ steps.autograder.outputs.points }} >> .github/scores
          ls -al >> .github/scores

      - name: make image
        uses: jruipinto/ImageMagick-action@v1
        run: convert -background lightblue label:@.github/scores .github/scores.png 


      # commit and push badges if badges have changed
      - name: Commit changes to scores
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/scores'
          git add '.github/scores.png'
          git commit -m "Add/Update scores" || exit 0
          git push origin scores
